version: "3"

services:
  container:
    image: byjg/static-httpserver
    labels:
      easyhaproxy.http.redirect_ssl: true
      easyhaproxy.http.host: test.xpto.us
      easyhaproxy.http.port: 80
      easyhaproxy.http.localport: 8080
      easyhaproxy.http.certbot: true


networks:
   default:
     name: easyhaproxy
     external: true
