# docker volume create certs_letsencrypt
# docker volume create certs_haproxy
# docker volume create portainer_data
# docker network create easyhaproxy


version: "3"

services:
  easyhaproxy:
    image: byjg/easy-haproxy:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs_letsencrypt:/certs/letsencrypt
#      - certs_haproxy:/certs/haproxy

    environment:
      EASYHAPROXY_DISCOVER: docker
      EASYHAPROXY_LABEL_PREFIX: easyhaproxy
      EASYHAPROXY_LETSENCRYPT_EMAIL: changeme@example.org
      EASYHAPROXY_SSL_MODE: "default"
      HAPROXY_CUSTOMERRORS: "true"
      HAPROXY_USERNAME: admin
      HAPROXY_PASSWORD: password
      HAPROXY_STATS_PORT: 1936

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "1936:1936/tcp"

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
     - portainer_data:/data portainer
     - /var/run/docker.sock:/var/run/docker.sock
    labels:
      easyhaproxy.http.redirect_ssl: true
      easyhaproxy.http.letsencrypt: true
      easyhaproxy.http.host: portainer.xpto.us
      easyhaproxy.http.port: 80
      easyhaproxy.http.localport: 9000


volumes:
  certs_letsencrypt:
    external: true
  certs_haproxy:
    external: true
  portainer_data:
    external: true


networks:
  default:
    name: easyhaproxy
    external: true


