---
apiVersion: v1
kind: Namespace
metadata:
  name: parking

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: parking-valida-me
  namespace: parking
  annotations:
    kubernetes.io/ingress.class: easyhaproxy
spec:
  rules:
    - host: valida.me
      http:
        paths:
          - backend:
              serviceName: parking-valida-me
              servicePort: 80
    - host: www.valida.me
      http:
        paths:
          - backend:
              serviceName: parking-valida-me
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: parking-valida-me
  namespace: parking
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: parking-valida-me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-valida-me
  namespace: parking
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: parking-valida-me
  template:
    metadata:
      labels:
        app: parking-valida-me
    spec:
      containers:
        - name: parking-valida-me
          image: byjg/static-httpserver
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '0.05'
              memory: '20Mi'
            requests:
              cpu: '0.05'
              memory: '20Mi'
          env:
            - name: TITLE
              value: "valida.me"
