stats:
  username: admin
  password: password
  port: 1936         # Optional (default 1936)

customerrors: true   # Optional (default false)

easymapping:
  - port: 80
    redirect:
      host1.local: https://host1.local
      www.host1.local: https://host1.local

  - port: 443
    ssl: true
    hosts:
      host1.local:
        containers:
          - container:8080
