{{- if .Values.serviceAccount.create -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "easyhaproxy-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "easyhaproxy-ingress.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "easyhaproxy-ingress.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "easyhaproxy-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
