{{- if .Values.serviceAccount.create -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "easyhaproxy-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "easyhaproxy-ingress.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  # - configmaps
  # - endpoints
  # - nodes
  - pods
  - services
  - namespaces
  # - events
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  # - ingresses/status
  # - ingressclasses
  verbs:
  - get
  - list
  - watch
# - apiGroups:
#   - "extensions"
#   - "networking.k8s.io"
#   resources:
#   - ingresses/status
#   verbs:
#   - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  # - watch
  # - create
  # - patch
  # - update
# - apiGroups:
#   - "discovery.k8s.io"
#   resources:
#   - endpointslices
#   verbs:
#   - get
#   - list
#   - watch
{{- end }}