# To test:
# curl -k -H "Host: host1.local" https://127.0.0.1/

version: "3"

services:
  haproxy:
    image: byjg/easy-haproxy
    volumes:
      - ./config.yml:/etc/haproxy/easyconfig.yml
      - ./certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      EASYHAPROXY_DISCOVER: static
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "1936:1936/tcp"

  container:
    image: byjg/static-httpserver
